--CREATE TABLE tasks(
--   id             INTEGER NOT NULL,
--   template_id    INTEGER NOT NULL,
--   title          VARCHAR(32) NOT NULL,
--   description    VARCHAR(64) NOT NULL,
--   text           TEXT NOT NULL
--);

--CREATE TABLE tasks_state(
--   id             INTEGER NOT NULL PRIMARY KEY,
--   template_id             INTEGER NOT NULL,
--   title VARCHAR(32) NOT NULL,
--   previous_department VARCHAR(64) NOT NULL,
--   current_department    VARCHAR(64) NOT NULL
--);

--CREATE TABLE templates(
--    id             INTEGER NOT NULL PRIMARY KEY,
--    description    VARCHAR(64) NOT NULL,
--    graph_nodes    TEXT NOT NULL,
--    graph_edges    TEXT NOT NULL
--);
