--CREATE TABLE departments(
--   id             INTEGER NOT NULL PRIMARY KEY,
--   name           VARCHAR(32) NOT NULL,
--   description    VARCHAR(64) NOT NULL,
--   is_available   BOOLEAN NOT NULL
--);
--
--insert into departments values (1, 'crm-zuul-ws', 'Роутер', true);
--insert into departments values (2, 'crm-customers-ws', 'Отдел клиентов', true);
--insert into departments values (3, 'crm-analytics-ws', 'Отдел аналитиков', true);
--insert into departments values (4, 'crm-developers-ws', 'Отдел разработчиков', true);
--
--
--
--CREATE TABLE templates(
--   id             INTEGER NOT NULL,
--   department_id    INTEGER NOT NULL REFERENCES departments(id),
--   next_department_id INTEGER NOT NULL REFERENCES departments(id)
--);